(define (rand message)
  (define current 100501)
  (define (new-rand x) (remainder (+ (* 14234324234234 x) 2892923) 10000))
  (define (reset new) (set! current new) current)
  (define (dispatch message)
    (cond ((eq? message 'generate) (set! current (new-rand current)) current)
          ((eq? message 'reset) reset)
          (else "Unknown request -- RAND")))
  (dispatch message))

(rand 'generate)
(rand 'generate)
(rand 'generate)
(rand 'generate)
((rand 'reset) 100500)
(rand 'generate)
(rand 'generate)
((rand 'reset) 100500)
(rand 'generate)
(rand 'generate)
